export const IMG = {
  bimDrafting: "/assets/bim-drafting.jpg",
  boardroom: "/assets/boardroom.jpg",
  civilWorks: "/assets/civil-works.jpg",
  cleanroom: "/assets/cleanroom.jpg",
  concretePour: "/assets/concrete-pour.jpg",
  electrical: "/assets/electrical.jpg",
  facade: "/assets/facade.jpg",
  foundation: "/assets/foundation.jpg",
  hero: "/assets/hero.jpg",
  joinery: "/assets/joinery.jpg",
  lobby: "/assets/lobby.jpg",
  officeInterior: "/assets/office-interior.jpg",
  plumbing: "/assets/plumbing.jpg",
  portraitInteriors: "/assets/portrait-interiors.jpg",
  portraitMd: "/assets/portrait-md.jpg",
  portraitMep: "/assets/portrait-mep.jpg",
  portraitOps: "/assets/portrait-ops.jpg",
  renovation: "/assets/renovation.jpg",
  restaurant: "/assets/restaurant.jpg",
  steelFrame: "/assets/steel-frame.jpg",
  superstructure: "/assets/superstructure.jpg",
  towers: "/assets/towers.jpg",
  university: "/assets/university.jpg",
  villa: "/assets/villa.jpg",
} as const;
